### ISSUE TITLE
Hoping for your result

### ISSUE THREAD

**Issue by jinfagang** [PlayVoice/vits_chinese#1]
Hoping for your result trained vits on Chinese

**Comment by dtx525942103** [comment]
i update

**Comment by jinfagang** [comment]
thanks, I'll try train it. Have u tested speed between vits and tactron2? Which do u think is better in terms of speed and quality?

**Comment by dtx525942103** [comment]
of course, vits is better.it is so amazing

**Comment by jinfagang** [comment]
how about inference speed?

**Comment by jinfagang** [comment]
Do u think it worthy to deploy (or reasonable) ? If so, I can help deploy to TensorRT and make a C++ inference demo, also, tvm also applicable if the speed is good.

**Comment by dtx525942103** [comment]
the vits_样本.wav is about 100 Seconds, it spends 800ms of a 1080 GPU to inference. if you need more fast, you can change the decoder from hifigan to mb melgan.

**Comment by dtx525942103** [comment]
the technology in vits: vae & normlizing flow & gan & mas & multi task train & adaptability to long sentences etc, i think it is a general frame work of tts in the future.

**Comment by jinfagang** [comment]
@dtx525942103 800ms for 100s, 20-30s need only 200ms, which is tolerrenable, if using TensorRT accelerate it, can be 3x faster average. Seems can be even run on some low level compute devices such as Raspberry pi.

**Comment by HallidayReadyOne** [comment]
Could you provide the training log? I found that loss_disc was Nan during training.

**Comment by dtx525942103** [comment]
@HallidayReadyOne your wav is 16K?
[train.log](https://github.com/dtx525942103/vits_chinese/files/7250635/train.log)

**Comment by dtx525942103** [comment]
@jinfagang your wav is 16K?
[train.log](https://github.com/dtx525942103/vits_chinese/files/7250657/train.log)

**Comment by HallidayReadyOne** [comment]
Yes. I directly downloaded the data mentioned in readme, then down sampled to 16K and trained, and found that loss was nan or inf.

**Comment by dtx525942103** [comment]
you can train lispeech use official vits first

**Comment by dtx525942103** [comment]
you can train ljspeech use official vits first

**Comment by HallidayReadyOne** [comment]
Ok, i will try. Thank you.

**Comment by HallidayReadyOne** [comment]
I think I have solved the problem, which is caused by the compilation of monotonic align. Thanks for help.

**Comment by dtx525942103** [comment]
en en
