### ISSUE TITLE
message = infosub[1] IndexError: list index out of range

### ISSUE THREAD

**Issue by SRbone** [PlayVoice/vits_chinese#100]
python vits_prepare.py -c ./configs/bert_vits.json

报错：
Traceback (most recent call last):
  File "vits_prepare.py", line 71, in <module>
    message = infosub[1]
IndexError: list index out of range

**Comment by MaxMax2016** [comment]
这个代码是专门处理000001-010000.txt的，不能处理其他文件

**Comment by SRbone** [comment]
哦哦，明白了，要自己改一改了

**Comment by SRbone** [comment]
python vits_prepare.py -c ./configs/bert_vits.json

报错：

torch/functional.py:641: UserWarning: stft with return_complex=False is deprecated. In a future pytorch release, stft will return complex tensors for all inputs, and return_complex=False will raise an error.
Note: you can still call torch.view_as_real on the complex output to recover the old return format. (Triggered internally at ../aten/src/ATen/native/SpectralOps.cpp:862.)
  return _VF.stft(input, n_fft, hop_length, win_length, window,  # type: ignore[attr-defined]
Traceback (most recent call last):
  File "vits_prepare.py", line 112, in <module>
    char_embeds = prosody.expand_for_phone(char_embeds, count_phone)
  File "/root/Vits-Chinese/master/bert/ProsodyModel.py", line 60, in expand_for_phone
    assert char_embeds.size(0) == len(length)
AssertionError

**Comment by MaxMax2016** [comment]
这是拼音长度和字符长度不一样引起的，这得看看你具体的文本和拼音是什么。

**Comment by SRbone** [comment]
train 起来了， 谢谢大佬。

INFO:bert_vits:====> Epoch: 13
INFO:bert_vits:Train Epoch: 14 [41%]
INFO:bert_vits:[2400, 9.983762181915804e-05]
INFO:bert_vits:loss_disc=2.649, loss_gen=2.033, loss_fm=2.344
INFO:bert_vits:loss_mel=35.640, loss_dur=1.434, loss_kl=0.717
INFO:bert_vits:loss_kl_r=1.857
INFO:bert_vits:Train Epoch: 14 [97%]
INFO:bert_vits:[2500, 9.983762181915804e-05]
INFO:bert_vits:loss_disc=2.444, loss_gen=2.253, loss_fm=2.712
INFO:bert_vits:loss_mel=40.834, loss_dur=1.334, loss_kl=0.686
INFO:bert_vits:loss_kl_r=2.124
INFO:bert_vits:====> Epoch: 14

**Comment by v-yunbin** [comment]
> 这是拼音长度和字符长度不一样引起的，这得看看你具体的文本和拼音是什么。

遇到同样的问题，合成文本是“据了解，截至目前，国内大模型厂商中提出追赶ChatGPT明确时间表的只有科大讯飞一家。”

**Comment by xiaoyin199** [comment]
数据集中有英文，就会报错，可以自己修改一下./bert/ProsodyModel.py， text2Token(self, text)方法，将英文处理一下就不报错，`   def text2Token(self, text):
        token = self.tokenizer.tokenize(text)
        # print(token)
        newToken = []
        for t in token:
            if re.match(r'^[a-zA-Z0-9]+$', t):
                itemSplit = [char for char in t]
                newToken.extend(itemSplit)
            else:
                newToken.append(t)
        # print(newToken)
        txtid = self.tokenizer.convert_tokens_to_ids(newToken)
        return txtid`
