### ISSUE TITLE
微调模型的时候，只加载优化模型D.pth?

### ISSUE THREAD

**Issue by huangmeimao** [PlayVoice/vits_chinese#101]
看您提供的log，再第二次微调训练时，仅预加载了D.pth，不用预加载G_xxx.pth吗？我如果不两个一起加载会出错。
另外，3千条句子可以训练出比较好的模型吗

**Comment by MaxMax2016** [comment]
继续训练G+D都加载了啊；做student模型压缩的时候，只加载G，因为decoder是从0开始训练的，加载D没意义；3000条无重复的句子，只能训出勉强可用的模型。

**Comment by huangmeimao** [comment]
非常感谢您的回复，如果我准备多人的音频，每个几百条数据，可以解决数据量少引起的发音效果差的问题吗？人数足够多

**Comment by MaxMax2016** [comment]
可以的啊，sovits就是这个思路
