### ISSUE TITLE
 No module named 'monotonic_align.monotonic_align'

### ISSUE THREAD

**Issue by Hujiazeng** [PlayVoice/vits_chinese#102]
执行python setup.py build_ext --inplace报错, 找不到monotonic_align\core.cp38-win_amd64.pyd, 

查看issues, 似乎不影响, 继续运行项目报错    from .monotonic_align.cores import maximum_path_c
ModuleNotFoundError: No module named 'monotonic_align.monotonic_align'

**Comment by yihuitang** [comment]
你在monotonic_align目录下再建一个空目录monotonic_align试试，我是这么解决的

**Comment by Hujiazeng** [comment]
似乎该文件夹没有工作

**Comment by yihuitang** [comment]
执行python setup.py build_ext --inplace之后还是空目录没事，不影响训练

**Comment by Hujiazeng** [comment]
谢谢您的帮助~
