### ISSUE TITLE
关于通过loss_kl_r进行finetune训练

### ISSUE THREAD

**Issue by huangmeimao** [PlayVoice/vits_chinese#103]
大佬，根据您其他问题的建议，我在第一次训练的时候，先把 loss_kl_r=0,训练的到以下情况，声音听起来还有很多读的不准确？
这个正常吗？可以开始第二阶段重新加上loss_kl_r,并冻结PosteriorEncoder吗?
LOG: 2023-06-29 15:09:18,527	bert_vits	INFO	loss_disc=2.641, loss_gen=1.992, loss_fm=3.197
2023-06-29 15:09:18,527	bert_vits	INFO	loss_mel=15.999, loss_dur=0.107, loss_kl=1.762
2023-06-29 15:09:18,527	bert_vits	INFO	loss_kl_r=0.000

我用的config直接用的默认配置，batch size是8，不是16.

音频见附件。
[wavs.zip](https://github.com/PlayVoice/vits_chinese/files/11907349/wavs.zip)

**Comment by MaxMax2016** [comment]
可以

**Comment by huangmeimao** [comment]
所以训练到现在这个程度是正常的了？感谢感谢

**Comment by MaxMax2016** [comment]
听上去音质比较正常了，可以加反向kl_loss拉低kl_loss了
