### ISSUE TITLE
如何处理Bert词表中没有的中文字符

### ISSUE THREAD

**Issue by tonywanggit** [PlayVoice/vits_chinese#104]
我在用AiShell3的数据集进行训练的时候发现有不少中文在Bert词表中没有，在实际的生产部署时候碰到这种情况应该如何处理？

例如：SSB03930415.wav 搜狐娱乐讯**渀**港媒报道

**Comment by MaxMax2016** [comment]
会被bert处理为unk吧，不用特别处理，最后这个字没韵律

**Comment by tonywanggit** [comment]
https://github.com/PlayVoice/vits_chinese/blob/master/vits_pinyin.py#L56C41-L56C41

从 vits_pinyin.py的代码来看，好像不支持UNK

**Comment by MaxMax2016** [comment]
看bert_vits那个分支

**Comment by tonywanggit** [comment]
@MaxMax2016 多谢提示，再问一下这两分支有什么区别呢，我看主分支也是用到了bert?

**Comment by MaxMax2016** [comment]
master有custom的代码
