### ISSUE TITLE
学习率相关

### ISSUE THREAD

**Issue by fangg2000** [PlayVoice/vits_chinese#105]
"learning_rate": 1e-4,
 "batch_size": 8,

目前我有8000个音频样本，显卡3060，我设置 **learning_rate＝2e-4** 的结果是loss收敛不佳且波动有点大，合成的音频也一般，不够自然和流畅还带点杂音，请问如果设置成上面这样是不是合适？

**Comment by fangg2000** [comment]
UP主周末云游去了么？现在经过200K的训练后，效果比之前相同的步数时好了很多，现在应该已经有了三品丹的成色……估计再过一晚就可以出炉了，祝UP主周末玩儿愉快啊

**Comment by MaxMax2016** [comment]
学习率的问题不好回答啊，很高兴你调好了
