### ISSUE TITLE
请问如何解决多音字，以及日期等阿拉伯数字的合成的问题

### ISSUE THREAD

**Issue by ShangkunTu** [PlayVoice/vits_chinese#108]
作者您好，根据您的代码，我用标贝女生训练了180000步，目前合成的语音质量已经很高了，但是多音字问题发音比较严重，比如"长大"读成chang大，等问题，另外就是不能合成阿拉伯数字。因为刚刚接触语音合成，很多事情不懂，如果特来请教，如果我想优化解决上面两个问题，请问我需要从哪些角度通过什么方式去解决呢？感谢~~！！！

**Comment by MaxMax2016** [comment]
可以从这里获得你想要的答案：https://github.com/wenet-e2e/wetts

**Comment by ShangkunTu** [comment]
> 可以从这里获得你想要的答案：https://github.com/wenet-e2e/wetts

非常感谢您的回复！请问一下再您工程的基础上，怎么使用AISHELL3训练一个多说话人的vits_chinese啊？能给点建议嘛

**Comment by ShangkunTu** [comment]
> 我建议您使用：https://github.com/wenet-e2e/wetts 训练AISHELL3，它提供了AISHELL3的训练程序；他们也使用了bert，在原理上区别不大了；他们有专业的技术团队提供技术支持；您可以看本项目历史issue，似乎本项目用于AISHELL3不容易成功。 本项目只能算做，入门项目。

作为初学者，诸多不懂，您的回复对我帮助非常大，感谢！
