### ISSUE TITLE
how to create baker_train.txt ????

### ISSUE THREAD

**Issue by donkey1020** [PlayVoice/vits_chinese#11]
how to create baker_train.txt ????

**Comment by dtx525942103** [comment]
use pypinyin change chinese to phones

**Comment by donkey1020** [comment]
谢谢 那怎么生成呢 我是新手 研究这个框架好几天了 没搞明白呢。 怎么用pypinyin 生成呢？

**Comment by donkey1020** [comment]
有py工具吗 那个 preprocess.py可以不

**Comment by donkey1020** [comment]
> 

pypinyin可以生成 ./baker_waves/000001.wav|sil k a2 #0 ^ er2 #0 p u3 #0 p ei2 #0 ^ uai4 #0 s uen1 #0 ^ uan2 #0 h ua2 #0 t i1 #0 sil eos 这种格式的拼音吗  大神能教一下不

**Comment by dtx525942103** [comment]
你参考下这个https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/processor/baker.py

**Comment by donkey1020** [comment]
谢谢

**Comment by donkey1020** [comment]
> 你参考下这个https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/processor/baker.py

大佬能在工程代码里添加上这个生成代码不？

**Comment by donkey1020** [comment]
> 你参考下这个https://github.com/TensorSpeech/TensorFlowTTS/blob/master/tensorflow_tts/processor/baker.py

谢谢 作者 我搞定了
