### ISSUE TITLE
如果要手动调整韵律应该怎么做呢？

### ISSUE THREAD

**Issue by iooops** [PlayVoice/vits_chinese#110]
因为韵律是嵌入的BERT embedding，如果模型有不准确的地方就不知道该怎么手动调整韵律/分词了

**Comment by MaxMax2016** [comment]
去掉韵律模型会呈现一个平均状态的韵律，没有韵律的起伏变化。

你可以试试修改推理，屏蔽bert韵律向量

def forward(self, x, x_lengths, bert):
x = self.emb(x) * math.sqrt(self.hidden_channels) # [b, t, h]
b = self.emb_bert(bert)
x = x + b
x = torch.transpose(x, 1, -1) # [b, h, t]

**Comment by iooops** [comment]
可是我还是需要韵律的啊

**Comment by MaxMax2016** [comment]
可以从这里获得你想要的答案：https://github.com/wenet-e2e/wetts

**Comment by iooops** [comment]
想问下作者大大有没有试过直接加分词的方式去训练模型？

**Comment by MaxMax2016** [comment]
> 想问下作者大大有没有试过直接加分词的方式去训练模型？

好久以前用过，如果分词是用bert实现的话，那其实也差不多了~
