### ISSUE TITLE
出现韵律模型不认识的字（[UNK]）应该如何修复？

### ISSUE THREAD

**Issue by jmaxzh** [PlayVoice/vits_chinese#111]
比如“先帝创业未半而中道崩殂,今天下三分,益州疲弊,此诚危急存亡之秋也。然侍卫之臣不懈于内,忠志之士忘身于外者,盖追先帝之殊遇,欲报之于陛下也。”中的“殂”字。

**Comment by MaxMax2016** [comment]
修复不了，但，影响不大
