### ISSUE TITLE
小白请教：RuntimeError: The size of tensor a (xxx) must match the size of tensor b (512) at non-singleton dimension 1

### ISSUE THREAD

**Issue by ZiqingYip** [PlayVoice/vits_chinese#112]
执行 "python vits_infer.py --config ./configs/bert_vits.json --model vits_bert_model.pth" 后报错如下错误：
RuntimeError: The size of tensor a (1220) must match the size of tensor b (512) at non-singleton dimension 1

初步排查下应该输入文本每行的文字数量过多导致的，请教下这种一般应该怎么处理？如何才能让模型为一个长文本的生成一段语音呢？

**Comment by MaxMax2016** [comment]
bert模型最大支持512个字输入（包括标点在内）
