### ISSUE TITLE
你好，请叫一下，我用标贝的素材训练到80W步，也没有你这个声音这么清脆，是什么问题？

### ISSUE THREAD

**Issue by mmmmm21** [PlayVoice/vits_chinese#113]
到底是什么问题？我看了网上一些人的标贝，声音非常干脆，但是我训练的虽然也可以，但是达不到你这个效果

**Comment by MaxMax2016** [comment]
你有用过原始vits训练没有呢，清脆不？

**Comment by MaxMax2016** [comment]
之前issue里面好像提过这个问题，可以试试，不加反向flow loss把模型训练好后，在加上它稍微训练一下。

**Comment by mmmmm21** [comment]
我是用这个项目：https://github.com/CjangCjengh/vits 来中文训练的，标贝训练80万的效果和别人的80W的效果差很多。
你的视频听下来，效果跟这个项目：https://github.com/rotten-work/vits-mandarin-windows 下面的80W的标贝很像，声音很干脆，清爽。
我自己的80W步的效果远不如你们的。
很疑惑。
我还是新手，不太懂你说的flow loss这些操作
