### ISSUE TITLE
发音不对

### ISSUE THREAD

**Issue by ISDHN** [PlayVoice/vits_chinese#115]
目前已经训练到第172epoch，每epoch42迭代，输出的声线是像的，但是吐字不对。
loss_mel= 24.643 loss_fm=3.378

**Comment by MaxMax2016** [comment]
loss mel 16 比较好，至少要低于18

**Comment by ISDHN** [comment]
谢谢，但是只会发出类似“正”的音，感觉很奇怪

**Comment by tanggang1997** [comment]
你好，我重新训练了vits，我的mel_loss一直在振荡，您训练的时候，loss的情况是怎么样的啊

**Comment by tanggang1997** [comment]
还有开头和末尾的sil一定要加上吗

**Comment by MaxMax2016** [comment]
> 还有开头和末尾的sil一定要加上吗

训练和推理保持一致就行，可以不加、如果训练音频前后空白不多的话

**Comment by MaxMax2016** [comment]
> 你好，我重新训练了vits，我的mel_loss一直在振荡，您训练的时候，loss的情况是怎么样的啊

标贝数据没出现振荡

**Comment by tanggang1997** [comment]
我看我的loss在1000多step的时候，就一直在振荡

**Comment by ISDHN** [comment]
> 你好，我重新训练了vits，我的mel_loss一直在振荡，您训练的时候，loss的情况是怎么样的啊

<img width="767" alt="image" src="https://github.com/PlayVoice/vits_chinese/assets/53806614/cbcb6291-bad1-4a35-8e41-bb29a74f72bd">

**Comment by ISDHN** [comment]
实际上lossmel在22附近时生产的音频就已经和训练样本差不多了

**Comment by tanggang1997** [comment]
> 显然lossmel在22附近时制作的音频已经和训练样本差不多了

我也不知道哪里出了问题，可能数据还是有问题，准备重新用这个训练了
