### ISSUE TITLE
字间间隔符

### ISSUE THREAD

**Issue by wizardk** [PlayVoice/vits_chinese#119]
你好，请问当前版本是不是在add_blank=False的基础上，字间的间隔符也去掉了？

比如这个：./data/waves/000001.wav|./data/berts/000001.npy|sil k a2 ^ er2 p u3 p ei2 ^ uai4 s uen1 ^ uan2 h ua2 t i1 sp sil
其中的k a2和^ er2之间已经没有字间的间隔符了

**Comment by MaxMax2016** [comment]
是的

**Comment by wizardk** [comment]
@MaxMax2016 https://huggingface.co/spaces/maxmax20160403/vits_chinese上的效果，和当前这个处理方式是一致的吗？

**Comment by MaxMax2016** [comment]
一致的，bert自带了字间间隔
