### ISSUE TITLE
这个训练出来 怎么控制 语速 音调 这些东西呀？？？？

### ISSUE THREAD

**Issue by donkey1020** [PlayVoice/vits_chinese#12]
这个训练出来 怎么控制 语速 音调 这些东西呀？？？？

**Comment by dtx525942103** [comment]
只有语速是可控的，其他不可控 net_g.infer(x_tst, x_tst_lengths, noise_scale=0, noise_scale_w=0, **length_scale**=1)[0][0,0].data.cpu().float().numpy()
