### ISSUE TITLE
aishell3模型似乎完全没有使用bert特征呀

### ISSUE THREAD

**Issue by TinaChen95** [PlayVoice/vits_chinese#130]
[多发音人与克隆，基于AISHELL3的预训练模型](https://github.com/PlayVoice/vits_chinese#%E5%A4%9A%E5%8F%91%E9%9F%B3%E4%BA%BA%E4%B8%8E%E5%85%8B%E9%9A%86%E5%9F%BA%E4%BA%8Eaishell3%E7%9A%84%E9%A2%84%E8%AE%AD%E7%BB%83%E6%A8%A1%E5%9E%8B)

不知道它为啥叫 vits_chinese....好像是基础的vits
有没有人试过多说话人的 vits_chinese 呀？求交流

**Comment by MaxMax2016** [comment]
可以用他的预训练模型，迁移训练，将节约90%的计算资源，毕竟bert向量只是拼接到了输入上面；后验编码器，Flow，HiFiGAN部分可以直接复用。

**Comment by YuChenDD** [comment]
@TinaChen95 见bert_vits_aishell3分支

**Comment by TinaChen95** [comment]
非常感谢！
