### ISSUE TITLE
训练数据中有标点符号怎么处理。

### ISSUE THREAD

**Issue by scriptboy1990** [PlayVoice/vits_chinese#150]
比如有一句“今天我，寒夜里看雪飘过”，转成的拼音要加逗号吗。还是直接"jin1 tian1 wo3 han2 ye4 li3 kan4 xue3 piao1 guo4"

**Comment by MaxMax2016** [comment]
标贝的标注里面只有拼音，实际上是需要的；在数据预处理的时候，通过同时遍历文本和拼音，把标点恢复并建模为sp了；当然也可以直接使用标点符号进行更精细建模。

**Comment by scriptboy1990** [comment]
> 标贝的标注里面只有拼音，实际上是需要的；在数据预处理的时候，通过同时遍历文本和拼音，把标点恢复并建模为sp了；当然也可以直接使用标点符号进行更精细建模。

再详细请教下哈，上次多人微调的已经可以训练了（第一批用来微调的数据集的极个别样本有逗号，但是转音素的时候碰到有标点符号好像被过滤了）。然后新的一批数据是几乎都有标点符号的，我这边具体应该怎么做呢。

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/vits_chinese/blob/bert_vits_aishell3/prep_bert.py#L97-L115

没有过滤，非汉字统一建模为 sp 了

**Comment by scriptboy1990** [comment]
> https://github.com/PlayVoice/vits_chinese/blob/bert_vits_aishell3/prep_bert.py#L97-L115
> 
> 没有过滤，非汉字统一建模为 sp 了

看了下代码，这里已经处理好了。
不过新的数据在微调时候遇到新的问题了：
<img width="1331" alt="image" src="https://github.com/PlayVoice/vits_chinese/assets/46958323/6d9dd972-9618-435f-966c-07162c8fff6f">
能提点下大概是哪里问题么，预处理方法和第一批数据一样的。

**Comment by scriptboy1990** [comment]
> > https://github.com/PlayVoice/vits_chinese/blob/bert_vits_aishell3/prep_bert.py#L97-L115
> > 没有过滤，非汉字统一建模为 sp 了
> 
> 看了下代码，这里已经处理好了。 不过新的数据在微调时候遇到新的问题了： <img alt="image" width="1331" src="https://user-images.githubusercontent.com/46958323/282465341-6d9dd972-9618-435f-966c-07162c8fff6f.png"> 能提点下大概是哪里问题么，预处理方法和第一批数据一样的。

已经解决。原因是在生成了bert的向量文件和all.txt后，我又处理了下all.txt把连续相邻的多个sp sp缩减为1个，导致维度不匹配。
