### ISSUE TITLE
支持多卡训练吗？

### ISSUE THREAD

**Issue by scriptboy1990** [PlayVoice/vits_chinese#151]
比如10张1080，如果支持的话，需要改哪里代码么。

**Comment by MaxMax2016** [comment]
支持，需要把学习率适当增大，多卡的时候 batch_size 实际为 卡数 * batch_size

**Comment by scriptboy1990** [comment]
> 支持，需要把学习率适当增大，多卡的时候 batch_size 实际为 卡数 * batch_size

在单块卡的情况下，我设置的batch_size为8
在n块卡的情况下，我设置batch_size为8 * n，但是运行的时候报CUDA out off memory，我重新设置为8，几张卡可以跑了。
但是我不确定不改batch_size的情况下，每张卡是不是都是跑的8个batchsize。😳

**Comment by MaxMax2016** [comment]
不改batch_size的情况下，每张卡都是跑的8个batchsize

**Comment by scriptboy1990** [comment]
> 不改batch_size的情况下，每张卡都是跑的8个batchsize

明白了。学习率有推荐的设置么，大概适当增大多少，六张卡。

**Comment by MaxMax2016** [comment]
"learning_rate": 1e-4 -> "learning_rate": 2e-4
