### ISSUE TITLE
二次元和aishell3这种数据能混在一起训练多说话人模型么。

### ISSUE THREAD

**Issue by scriptboy1990** [PlayVoice/vits_chinese#153]
想训练 一个通用点的底模，比如把二次元的数据集（例如原神）和aishell3，或者其他一些正常语气的放一起训练，效果会比单独的二次元训练效果好么？不知道作者有没有这方面尝试。

**Comment by MaxMax2016** [comment]
您可以先所有数据一起训练，然后在各个子数据集上面微调
