### ISSUE TITLE
大佬我训练出来的音频 语速太快，读的之间好像没有间隔。这个怎么解决？

### ISSUE THREAD

**Issue by donkey1020** [PlayVoice/vits_chinese#16]
大佬我训练出来的音频 语速太快，读的之间好像没有间隔。这个怎么解决？
大佬可以听一下 看看
链接: https://pan.baidu.com/s/1ZNaFXFkSDNH6WKIhWHhBzw 提取码: h0oj 
--来自百度网盘超级会员v1的分享

**Comment by dtx525942103** [comment]
样例的音素序列是怎么样的？
