### ISSUE TITLE
'monotonic_align.monotonic_align'

### ISSUE THREAD

**Issue by zhengyongchoa** [PlayVoice/vits_chinese#17]
大佬， 执行 python setup.py build_ext --inplace

Compiling core.pyx because it changed.
copying build/lib.linux-x86_64-cpython-37/monotonic_align/core.cpython-37m-x86_64-linux-gnu.so -> monotonic_align
error: could not create 'monotonic_align/core.cpython-37m-x86_64-linux-gnu.so': No such file or directory

 这是什么问题？

**Comment by zhengyongchoa** [comment]
工程代码需要放置在linux系统的根目录下吗？

**Comment by dtx525942103** [comment]
不需要啊，这个问题我也没遇到过，

**Comment by Owen-Fish** [comment]
https://github.com/jaywalnut310/vits/issues/56#issuecomment-1181206842
