### ISSUE TITLE
有出Java版的计划吗？

### ISSUE THREAD

**Issue by watersoft123** [PlayVoice/vits_chinese#18]
想在手机上离线使用，是否有出Java版的计划？

**Comment by dtx525942103** [comment]
这个在手机上跑不起来，需要GPU

**Comment by watersoft123** [comment]
> 这个在手机上跑不起来，需要GPU

挺遗憾的，好多人工智能的东西都是用Python实现的，Java的很少。
手机也有GPU吧，只不过是集成的，另外训练阶段用到GPU，如果在电脑上训练好了，在手机上使用应该对GPU要求不高吧

**Comment by biaji** [comment]
同样想知道只进行推理的话，目前比较新的硬件是不是能支撑了。
