### ISSUE TITLE
question about the phone seqs

### ISSUE THREAD

**Issue by FanhuaandLuomu** [PlayVoice/vits_chinese#19]
hello, can u explain for the filelists's phone seqs.
such as 
./baker_waves/000016.wav|sil c ii3 #0 ^ uai4 #0 g uang2 #0 b en3 #0 sp ^ ie3 #0 j iang1 #0 ^ iou2 #0 sh ao4 #0 zh uang4 #0 p ai4 #0 zh ang2 #0 g uan3 #0 sil eos

^  #0 mean what? and why not you add #1 #2 #3 etc?

**Comment by dtx525942103** [comment]
this label is from MFA

**Comment by dtx525942103** [comment]
^ is 0 声母；#0 is word edge.
