### ISSUE TITLE
NameError: name 'm_frame' is not defined

### ISSUE THREAD

**Issue by DWGIII** [PlayVoice/vits_chinese#20]
最新代码运行，出现了这个错误
File "vits_chinese\models.py", line 583, in forward
    z_frame = m_frame + torch.randn_like(m_frame) * torch.exp(logs_frame)
NameError: name 'm_frame' is not defined

**Comment by cat1222** [comment]
同问，m_frame和logs_frame两个参数是哪来的？

**Comment by MaxMax2016** [comment]
已改，之前额外添加网络处理m_p和logs_p，好像没什么用就删除了

**Comment by cat1222** [comment]
@MaxMax2016 thx！

**Comment by MaxMax2016** [comment]
train里面的loss也改改
