### ISSUE TITLE
stft.py line 199报错：runtimeerror: exp does not support automatic differentiation for outputs with complex dtype.

### ISSUE THREAD

**Issue by cat1222** [PlayVoice/vits_chinese#21]
module.py line 295,in forward
out = self.stft.inverse(spec, phase).to(x.device)
stft line 199 in inverse
magnitude*torch.exp(phase*1j),
runtimeerror: exp does not support automatic differentiation for outputs with complex dtype.

**Comment by cat1222** [comment]
大佬，除了更新torch版本以外还有别的解决方法吗？我这边环境torch1.7.0的版本，升1.9需要改cuda环境，我暂时没这个权限。。。

**Comment by MaxMax2016** [comment]
Maybe you can use torch.cos(z) + 1j * torch.sin(z) instead **exp**.

**Comment by cat1222** [comment]
thx！问题已解决，用了您的方法后还有个小错误，最后改成：（torch.cos(z)).type(torch.complex64) + 1j * (torch.sin(z)).type(torch.comlpex64)，这个错误就通过了。

然后迎来了下一个报错：
train.py  line 401——》
unbouondlocalerror: local variable 'x' referenced before assignment.
不会是因为版本问题会带来一些列的连锁反应吧

**Comment by MaxMax2016** [comment]
应该不是，这个错是说x没有定义

**Comment by cat1222** [comment]
搞到外网环境来跑可以训练了，公司内网的GPU资源真的是无用良品。。。。
总之，谢谢大佬的耐心解答～～ @MaxMax2016
