### ISSUE TITLE
大佬，用项目提供的数据集，训了250 epoch+时，感觉loss都不怎么下降了，这是训练到位了吗？

### ISSUE THREAD

**Issue by cat1222** [PlayVoice/vits_chinese#22]

**Comment by cat1222** [comment]
INFO:baker_base:Train Epoch: 252 [49%]
INFO:baker_base:[152400, 0.00019382203747381871]
INFO:baker_base:loss_disc=2.019, loss_gen=2.860, loss_fm=7.248
INFO:baker_base:loss_mel=14.697, loss_dur=0.179, loss_kl=0.574
INFO:baker_base:Train Epoch: 252 [82%]
INFO:baker_base:[152600, 0.00019382203747381871]
INFO:baker_base:loss_disc=2.412, loss_gen=2.386, loss_fm=6.320
INFO:baker_base:loss_mel=14.754, loss_dur=0.170, loss_kl=0.360
INFO:baker_base:====> Epoch: 252
===============epoch use time: 293.3362545967102
INFO:baker_base:Train Epoch: 253 [15%]
INFO:baker_base:[152800, 0.0001937978097191345]
INFO:baker_base:loss_disc=2.233, loss_gen=2.566, loss_fm=6.897
INFO:baker_base:loss_mel=14.915, loss_dur=0.146, loss_kl=0.772

**Comment by MaxMax2016** [comment]
这个loss很小了啊，我一般mel在16, kl在1

**Comment by cat1222** [comment]
训练效果大概是这个样子：
链接:https://pan.baidu.com/s/1CdG0Rr9Ug0NsaETvPsXBMQ  密码:psjn

**Comment by cat1222** [comment]
训练效果大概是这个样子：
链接:https://pan.baidu.com/s/1CdG0Rr9Ug0NsaETvPsXBMQ  密码:psjn

**Comment by MaxMax2016** [comment]
是这样的

**Comment by cat1222** [comment]
但是感觉语间停顿还有些问题，还有一些数值型的内容会漏报。这些问题是需要进一步优化模型才能提升是吗？

**Comment by MaxMax2016** [comment]
要加韵律预测模型和文本前端

**Comment by cat1222** [comment]
哈哈哈哈，那我蹲一下，您更新了踢我

**Comment by MaxMax2016** [comment]
行

**Comment by cat1222** [comment]
或则会您有什么思路可以分享，我们一起搞。但是我刚入门，还是小白，需要和您多学习

**Comment by MaxMax2016** [comment]
[face_frames, face_coords, ](https://github.com/Executedone/Chinese-FastSpeech2)我基于这个方法实现了，效果不错；wetts也在做这方面，做的还挺好的。

**Comment by cat1222** [comment]
Thx!!!

**Comment by MaxMax2016** [comment]
@cat1222 下载预训练模型试试

**Comment by cat1222** [comment]
来啦来啦，这就去试试～～

**Comment by cjia4** [comment]
> 要加韵律预测模型和文本前端，我还在梳理、会释放~星星好少，没动力更新~~~

给了星了，大神加油搞。。   😁

等着你的更新

**Comment by ydnnh2008** [comment]
給星了

**Comment by wxbool** [comment]
> 要加韵律预测模型和文本前端，我还在梳理、会释放~星星好少，没动力更新~~~

要怎么联系您呢，希望可以跟您交流合作，我的邮箱：wangxin8@foxmail.com 。方便的话可以发一封邮件给我，发下您的联系方式
