### ISSUE TITLE
问题：推理错误，语调不对

### ISSUE THREAD

**Issue by jinfagang** [PlayVoice/vits_chinese#25]
```
孩子，别吃了，这里的肉脏，走跟我去太平间
你好呀，这是一个美丽的早晨，我希望你能知道我有多爱你
愿你的努力得到回报，心中充满喜悦和满足。祝你拥有美好的一天！
愿你在新的一天里充满能量和活力，享受每一个美好的瞬间，迎接新的挑战和机遇。

```

这几句话会出现错误：

```
vits_chinese/bert/ProsodyModel.py", line 60, in expand_for_phone
    assert char_embeds.size(0) == len(length)
AssertionError
```

第一句话语调非常不对。

**Comment by MaxMax2016** [comment]
孩子，别吃了，这里的肉脏，走跟我去太平间
你好呀，这是一个美丽的早晨，我希望你能知道我有多爱你
愿你的努力得到回报，心中充满喜悦和满足，祝你拥有美好的一天
愿你在新的一天里充满能量和活力，享受每一个美好的瞬间，迎接新的挑战和机遇

这个还在完善中，没包含多音字预测和文本正则，需要手动处理
[bert_out.zip](https://github.com/PlayVoice/vits_chinese/files/10799614/bert_out.zip)

**Comment by jinfagang** [comment]
怎么解决的？有push代码？

**Comment by jinfagang** [comment]
我这里推理错误。。。。

**Comment by MaxMax2016** [comment]
还没添加相关代码，后面会尝试
