### ISSUE TITLE
请问BERT模型是如何训练的呢？

### ISSUE THREAD

**Issue by TinaChen95** [PlayVoice/vits_chinese#26]
请问bert模型用的是bert-base-chinese吗？是在什么语料上训练的呢？

**Comment by MaxMax2016** [comment]
目前，我直接使用这个项目的https://github.com/Executedone/Chinese-FastSpeech2，相关资料在https://zhuanlan.zhihu.com/p/585086910

**Comment by TinaChen95** [comment]
感谢大佬指路！
