### ISSUE TITLE
Can I use this to train with 32K sampling audio data?

### ISSUE THREAD

**Issue by ewayboy** [PlayVoice/vits_chinese#29]
Thanks for your great job.
And this project can be used to train with 32k sampling audio data? I had changed the  config file with sampling rate from 16K to 32K, and my own data is 32K, preprocess all done. but when i go to train work, it shows the following error: RuntimeError: the expanded size of the tensor (68) must match the existing size (70) at non-singleton dimension 0. Target sizes: [68,256]. Tensor sizes: [70,256]

**Comment by MaxMax2016** [comment]
can you paste your conf?

**Comment by ewayboy** [comment]
{
  "train": {
    "log_interval": 100,
    "eval_interval": 10000,
    "seed": 1234,
    "epochs": 20000,
    "learning_rate": 1e-4,
    "betas": [0.8, 0.99],
    "eps": 1e-9,
    "batch_size": 8,
    "fp16_run": false,
    "lr_decay": 0.999875,
    "segment_size": 12800,
    "init_lr_ratio": 1,
    "warmup_epochs": 0,
    "c_mel": 45,
    "c_kl": 1.0
  },
  "data": {
    "training_files":"filelists/train.txt",
    "validation_files":"filelists/valid.txt",
    "max_wav_value": 32768.0,
    "sampling_rate": 32000,
    "filter_length": 1024,
    "hop_length": 256,
    "win_length": 1024,
    "n_mel_channels": 80,
    "mel_fmin": 0.0,
    "mel_fmax": null,
    "add_blank": false,
    "n_speakers": 0
  },
  "model": {
    "inter_channels": 192,
    "hidden_channels": 192,
    "filter_channels": 768,
    "n_heads": 2,
    "n_layers": 6,
    "kernel_size": 3,
    "p_dropout": 0.1,
    "resblock": "1",
    "resblock_kernel_sizes": [3,7,11],
    "resblock_dilation_sizes": [[1,3,5], [1,3,5], [1,3,5]],
    "upsample_rates": [8,8,2,2],
    "upsample_initial_channel": 512,
    "upsample_kernel_sizes": [16,16,4,4],
    "n_layers_q": 3,
    "use_spectral_norm": false
  }
}

**Comment by ewayboy** [comment]
After I converted data from 32K to 16K, it pop up the same error.

**Comment by MaxMax2016** [comment]
this mean prosody embedding from BERT is not as long as your phone sequence, i just test on baker-data，for other data you should check where makes this error.

**Comment by ttkrpink** [comment]
> Thanks for your great job. And this project can be used to train with 32k sampling audio data? I had changed the config file with sampling rate from 16K to 32K, and my own data is 32K, preprocess all done. but when i go to train work, it shows the following error: RuntimeError: the expanded size of the tensor (68) must match the existing size (70) at non-singleton dimension 0. Target sizes: [68,256]. Tensor sizes: [70,256]

Did you find a solution for this? I had the same problem.

> RuntimeError: The expanded size of the tensor (41) must match the existing size (43) at non-singleton dimension 0.  Target sizes: [41, 256].  Tensor sizes: [43, 256]
