### ISSUE TITLE
Infer loss from NaturalSpeech

### ISSUE THREAD

**Issue by wizardk** [PlayVoice/vits_chinese#33]
请问在代码里哪里体现参考NaturalSpeech的损失函数了？

**Comment by MaxMax2016** [comment]
https://github.com/PlayVoice/vits_chinese/blob/master/models.py#549~550
https://github.com/PlayVoice/vits_chinese/blob/master/train.py#264

**Comment by wizardk** [comment]
@MaxMax2016 再问下，加和不加这个损失，做过对比吗？效果差异明显吗？

**Comment by MaxMax2016** [comment]
在标贝数据集上，发音错误少些；VITS的发音错误一直被诟病。
