### ISSUE TITLE
关于音素生成一些疑问

### ISSUE THREAD

**Issue by suzhenghang** [PlayVoice/vits_chinese#38]
1 这两种有什么区别？
[会每个中间插入#0](https://github.com/UEhQZXI/vits_chinese/blob/35e6e41fa15835f2420d0c94da91daddf3513516/vits_strings.py#L465)
[不会插入#0](https://github.com/PlayVoice/vits_chinese/blob/master/vits_prepare.py#L105)

2 准备好的文本有标点符号和没标点符号训练出来差别会大嘛？

**Comment by MaxMax2016** [comment]
bert使用是用#0~#4训练的，所以这些信息已经在bert的向量里面了，没必要在拼音中间重复添加。

**Comment by suzhenghang** [comment]
了解了，那准备的文本中逗号、句号等标点符号加与不加会效果差别大嘛？

**Comment by MaxMax2016** [comment]
影响很大，没有标点停顿不自然
