### ISSUE TITLE
how to export to onnx?

### ISSUE THREAD

**Issue by jinfagang** [PlayVoice/vits_chinese#4]
Will op consider add deploy to vits like using onnxruntime or tensorrt accelerate?

**Comment by dtx525942103** [comment]
@jinfagang 大神，我正在向您请教如何实现onnx导出！现在用的libtorch

**Comment by martin3252** [comment]
@dtx525942103 @jinfagang 请问有成功用onnx 或jit转换模型吗？ 我用onnxruntime推論會報錯,使用jit轉換失敗

**Comment by dtx525942103** [comment]
onnx导出成功了，但是输入长度被固定了，无法处理其他长度的句子；jit正常导出了；使用这个项目无法导出jit，可以参考wenet的代码，按照错误提示进行修改即可；由于工作原因，这个修改不能上传；

**Comment by martin3252** [comment]
@dtx525942103 感谢你的回覆,那方便提供onnx的代码吗

**Comment by dtx525942103** [comment]
是同一套，只是导出指令不同

**Comment by martin3252** [comment]
了解，那可以提供wenet的专案项目位置吗，谢谢？

**Comment by dtx525942103** [comment]
https://github.com/wenet-e2e/wenet 主要关注他们方法接口怎么设置参数，还有要把循环手动展开

**Comment by martin3252** [comment]
好的,谢谢你的回覆

**Comment by OnceJune** [comment]
@dtx525942103 请教一下我在导出jit的时候，flow部分会报错说：
`reversed(Tensor 0) -> (Tensor 0):`
`Expected a value of type 'Tensor' for argument '0' but instead found type '__torch__.torch.nn.modules.container.___torch_mangle_21.ModuleList (of Python compilation unit at: 0x564d213985d0)'.`
这个问题是怎么解决的？谢谢。

**Comment by dtx525942103** [comment]
@OnceJune 把      for flow in self.flows: x = flow(x, x_mask, g=g, reverse=reverse) 手动展开，用self.flows[0] self.flows[1]~进行访问

**Comment by OnceJune** [comment]
@dtx525942103 可以了，多谢大佬

**Comment by dtx525942103** [comment]
@OnceJune 不客气

**Comment by nicken** [comment]
成功的各位，方便提供一下onnx和onnxruntime的版本么？
