### ISSUE TITLE
关于音频中的静音段问题

### ISSUE THREAD

**Issue by hermanseu** [PlayVoice/vits_chinese#42]
请教个问题：关于音频中的比较长静音段(200ms以上)，大家是怎么处理的？需要在对应的音素序列位置插入了符号进行占位吗？

**Comment by MaxMax2016** [comment]
对于特别长的静音端，可以使用工具如audiosegment剪裁掉，当然使用占位符也可以的。

**Comment by hermanseu** [comment]
我现在是使用占位符处理的，觉的前期数据处理特别费事。 如果通过工具裁剪掉的话，你那容忍存留下来的静音长度最大是多少呢？

**Comment by MaxMax2016** [comment]
一个逗号停顿的长度

**Comment by hermanseu** [comment]
所以工具裁减掉静音后，音素序列中没有使用占位符对静音进行占位，音频中存留下的静音都通过blank吸收了？逗号的停顿长度是多少，300ms？

**Comment by MaxMax2016** [comment]
逗号停顿一般300ms~500ms吧，可以用blank去吸收；这里没用使用blank，而是使用bert，它能感知上下文信息，将停顿合理的合并进音素，当然这里的停顿应该是满足汉语停顿规则的自然停顿；如果是非自然的停顿，如结巴，可能需要用AdaVITS的框架去训练发音人了，即时长预测使用精标数据去训练。

**Comment by hermanseu** [comment]
了解了，谢谢

**Comment by MaxMax2016** [comment]
AdaVITS的框架：可以用GlowTTS+FreeVC拼出来
