### ISSUE TITLE
RuntimeError: The size of tensor a (76) must match the size of tensor b (84) at non-singleton dimension 1

### ISSUE THREAD

**Issue by jayne-ho** [PlayVoice/vits_chinese#47]
RuntimeError: The size of tensor a (76) must match the size of tensor b (84) at non-singleton dimension 1
请教这个如何解决

**Comment by MaxMax2016** [comment]
prepare代码是正对baker数据专门写的，这个错误是扩展后的bert向量和phone不一样长，需要排查prepare的过程，看是否是什么特殊字&符号导致的问题。

**Comment by AwakingsWings** [comment]
@jayne-ho 如果是昨天晚上之前clone的话，尝试pull一下,这个问题应该已经被解决了。
