### ISSUE TITLE
大神你好，我是tts小白，想求教些问题，希望不吝赐教，感谢

### ISSUE THREAD

**Issue by YangangCao** [PlayVoice/vits_chinese#52]
1.本项目如果去掉了bert这个模型会怎样
2.本项目是否支持中英文，比如“今天想去开party”
3.合成速度如何

**Comment by YangangCao** [comment]
还有个问题，请问这个库https://github.com/UEhQZXI/vits_chinese和本项目有啥关系吗

**Comment by MaxMax2016** [comment]
> 1.本项目如果去掉了bert这个模型会怎样 2.本项目是否支持中英文，比如“今天想去开party” 3.合成速度如何

1，去掉会导致不期望的停顿
2，baker数据只有中文
3，提供了模型测试，以及蒸馏和流式加速
4，bert蒸馏本项目不关注

**Comment by YangangCao** [comment]
感谢大神的回复🙏，想最后请教一个问题，我们最近想做voice conversion，搜集一个人的几句话再加上文本就直接出这个人朗读文本的语音。搜集几句话到输出最终语音期间只进行推理而不训练模型（想一个模型解决所有的voice conversion），这个能做到吗？有没有推荐的开源库

**Comment by MaxMax2016** [comment]
https://vallex-demo.github.io/ 微软的，没开源

**Comment by YangangCao** [comment]
好滴 了解了 感谢哈🙏
