### ISSUE TITLE
句尾吞音

### ISSUE THREAD

**Issue by AwakingsWings** [PlayVoice/vits_chinese#54]
@MaxMax2016  你有没有遇到过句尾字的发音非常混的情况？
使用自定义多说话人代码（改了不少东西，但框架没变），样本4个人，大概4个小时的样本，2000epoch后（生成器有点过拟合了），仍有一定概率会出现吞音的情况。
我的确加了一些东西，我往里面加了情感embedding，把embedding的发音和bert的残差加改成了发音、情感、bert的concat后过relu全连接到原始尺寸。但我确认应该不会是情绪的锅，在测试时不论怎么更改情绪，都还是同样的吞音。
你觉得是本身发音导致的问题还是bert导致的这个问题呢？
[output_audio.zip](https://github.com/PlayVoice/vits_chinese/files/11120957/output_audio.zip)

**Comment by MaxMax2016** [comment]
时长预测对不对？

**Comment by AwakingsWings** [comment]
时长预测是对的，到内个位置突然哑火，但是能明显感觉到比平常的停顿要长。

**Comment by MaxMax2016** [comment]
这个我也说不上来什么原因？1-3和3是同样的模型，1-3没吐音，3吐音，是这样的吧。

**Comment by AwakingsWings** [comment]
1-3和3是同样的模型，（名称无特殊含义，只是随手加的）。他们的输入仅有情绪编码不同。
主要想表达的意思是，“听着鸟鸣渐渐变()，触着清风渐渐变(）。” 括号内的部分不论情绪编码怎么改变，他们就是没了。被吞了，我想应该不是情绪的问题，就问问看你有没有遇到过这种情况。
我在尝试把输入transformer的维度改大，如果你也没有遇到过这种可能就是信息加的太多了，原来192表达能力不够。

**Comment by MaxMax2016** [comment]
会不会训练语料里面，最后一个字太小声了？

**Comment by AwakingsWings** [comment]
呃，这句话并不在样本里，我用的是我自定义的数据集，所以应该没有这句话。
我刚刚仔细听了一下，我认为我的样本中“结束时渐弱”的样本量很少，不至于达到这种情况。况且，问题也发生在倒数第二句不是么？
另外想问一下，你当时把bert(x256）打进去的时候，为什么想的是先过全连接到192在残差加，而不是concat后改超参数 或者concat后过全连接呢？（我也有点怀疑，是否是我concat后在过全连接相比于你的残差加弱化了本音embedding，但这倒是难以解释为什么出问题的地方一定在句尾。）

**Comment by MaxMax2016** [comment]
我往里面加了情感embedding，把embedding的发音和bert的残差加改成了发音、情感、bert的concat后过relu全连接到原始尺寸。
会不会通道数多的信息权重比较大？

**Comment by AwakingsWings** [comment]
发音 192
情感 1024
bert 256
你这么一说确实可能，但我一开始的时候没往呢方面想。因为我尝试过（bert concat 情感）过全连接到192然后残差加，效果很差-。-
从理论上来说，我看这个输入最后过了transformer encoder，而且没有加位置编码。按我的理解（可能不对），如果没有顺序关系的影响，这个数量级的差距应该不会对特征提取造成较大的影响吧。
但从另一个角度上来说，我也认可你的质疑。因为实际上来说，192维的发音就来自214个独立点（按我们之前改的内个时候的符号表，符号只有"sil", "sp"），以这个为基准而言大家彼此的信息量确实不在一个量级上。
我可能会尝试给这个1024加dropout,或者什么其他的办法试试。

**Comment by MaxMax2016** [comment]
“我看这个输入最后过了transformer encoder，而且没有加位置编码。”
它的encoder里面用了个滑动窗

**Comment by MaxMax2016** [comment]
"几乎没有范式指导我们在卷积之前加全连接"

conformer好像试全连接和卷积交叠使用的

**Comment by AwakingsWings** [comment]
-。-他这种架构我确实没见过（transformer套transformer）。但他这种一定要两个全连接层夹着卷积和注意力的汉堡包式画图法，让我想起了中学老师教完全平方公式里(a+b)^2 = a^2+2ab+b^2 一定不能写成a^2+b^2+2ab.
我做cv的工作比较多，如果cv的理解在nlp tts这边不适用的话，那可能这种理解是我偏后考虑的要素吧。
