### ISSUE TITLE
Which paper is Prosody Bert based on?

### ISSUE THREAD

**Issue by OswaldoBornemann** [PlayVoice/vits_chinese#57]
Which paper is Prosody Bert based on?

**Comment by MaxMax2016** [comment]
Reference For TTS
[Microsoft's NaturalSpeech: End-to-End Text to Speech Synthesis with Human-Level Quality](https://arxiv.org/abs/2205.04421)

https://github.com/Executedone/Chinese-FastSpeech2 bert prosody  <---------- this

https://github.com/wenet-e2e/WeTextProcessing

https://github.com/jaywalnut310/vits

**Comment by PPGGG** [comment]
@MaxMax2016 Yeah I noticed that. But i could not find the related paper from the given repo (which is the Chinese-FastSpeech2)

**Comment by MaxMax2016** [comment]
@PPGGG this is the blog from author, https://zhuanlan.zhihu.com/p/585086910
