### ISSUE TITLE
请问音频采样率一定要16khz吗？

### ISSUE THREAD

**Issue by zhao-cs-debug** [PlayVoice/vits_chinese#59]
我有采样率24khz的音频，我更改了采样率16khz。运行vits_prepare.py程序发现报错了
10
10
000037  揶揄得孙垚差点背过气儿。
except: list index out of range
8
8
000047  本山也真太抠门儿了。
except: list index out of range

请问是什么原因？有什么办法可以解决这个问题吗？

**Comment by MaxMax2016** [comment]
这个是数组越界，需要具体定位为是怎么越界了

**Comment by zhao-cs-debug** [comment]
是的。我做不出判断是哪出现了问题。有近100个数据出现了这个问题。会对最终结果有影响吗，在训练过程中会不会跳过这部分的数据呢

**Comment by MaxMax2016** [comment]
这个是儿化音的问题，由于没做相关研究，这块处理的比较简单。对后续没影响，只是这个模型不支持儿化音。

**Comment by zhao-cs-debug** [comment]
感谢
