### ISSUE TITLE
关于ZeroShot

### ISSUE THREAD

**Issue by suzhenghang** [PlayVoice/vits_chinese#60]
大佬有打算后续做下ZeroShot的工作嘛？或者有了解过ZeroShot目前性能怎样啊？

**Comment by MaxMax2016** [comment]
这个ZeroShot都是靠语料和算力堆起来的，这个~~做不了啊

**Comment by TinaChen95** [comment]
是不是可以用 external speaker embedding + aishell3 试一试？
看到另一个讨论里面，多说话人效果变差。不太确定这个变差是差了多少。
想请教下算力上预估会需要多少，以及您是怎么预估的呢？

**Comment by scriptboy1990** [comment]
> 这个ZeroShot都是靠语料和算力堆起来的，这个~~做不了啊

可以进一步解释下吗，为啥是靠算力推起来的
