### ISSUE TITLE
关于quantization

### ISSUE THREAD

**Issue by pgolds** [PlayVoice/vits_chinese#61]
大佬是否对量化有过研究，能达到什么样的性能

**Comment by MaxMax2016** [comment]
量化在TTS中很少人用吧，这样会这导致音频噪声的吧？语音转文本做量化倒是常见

**Comment by pgolds** [comment]
我转成openvino FP16格式的测试了下，听感上没太大区别，CPU合成速度能提升1/3。GPU使用的话我试了转TensorRT目前有问题，encoder里有不支持的类型，不知道该如何才能转化。

**Comment by MaxMax2016** [comment]
@pgolds 希望这个项目能解决你的问题：https://github.com/rhasspy/piper/tree/master/src/python/piper_train

**Comment by pgolds** [comment]
感谢，我看看
