### ISSUE TITLE
是否有计划支持多发音人？

### ISSUE THREAD

**Issue by alphonz** [PlayVoice/vits_chinese#63]
首先非常感谢大佬的仓库，算是试了若干个效果最好的一个了
未来是否有计划兼容多发音人呢，非常感谢🙏

**Comment by MaxMax2016** [comment]
受限于数据和算力，无法提供多发音人预训练模型；
VITS本身是支持多人的，issue里面也有人实现了。
https://github.com/PlayVoice/vits_chinese/issues/40
