### ISSUE TITLE
segment_size问题

### ISSUE THREAD

**Issue by pgolds** [PlayVoice/vits_chinese#64]
大佬，segment_size这个参数具体有什么影响，我看原版项目设置的是8192，本项目设置的12800。
现在我混合了多个数据集进行训练的时候采用12800会出现分割的错误
![image](https://user-images.githubusercontent.com/17938613/233256503-ed4640c1-4e1e-407a-a25f-f53648a1b570.png)
使用8192参数就能正常训练

**Comment by MaxMax2016** [comment]
segment_size需要是hop_length的整数倍，segment_size太大占用GPU显存过大，适当就好

**Comment by pgolds** [comment]
@MaxMax2016 大佬再问下，文本通过bert转换后的长度大小是怎么和转id表后长度一致的。我把id表换成中英文音素的id表后，输入文本通过bert计算出来的长度大小和转音素id长度不一致会造成推理的时候 x + self.emb_bert(bert) 错误,。我通过设置bert为None后可以正常推理，但语速快没有停顿，手动延长标点的停顿就稍微好些. 还有一种我通过填充bert后的长度达到和input_ids长度一致也可以正常推理了，中文部分相比少bert情况下好些，但英文情况下还是有连读情况。

**Comment by MaxMax2016** [comment]
bert使用的字符，每个字符有多个发音单元，中文两个、英文n个，标点符号这里定义为sp一个单元，将每个字符的bert向量根据字符对应的发音单元的个数进行复制拓展。

**Comment by pgolds** [comment]
意思是假如我1个中文是对应3个发音单元，是把这个中文字符的bert向量往后顺序复制3次嘛。英文也是同理么

**Comment by MaxMax2016** [comment]
是的

**Comment by pgolds** [comment]
好的，感谢大佬指点
