### ISSUE TITLE
建模单元

### ISSUE THREAD

**Issue by zdj97** [PlayVoice/vits_chinese#70]
您好，symbols的建模单元中，^ #0 #1 #2 #3 eos sp 这些具体的含义是什么呢？sil是静音把

**Comment by MaxMax2016** [comment]
^ 是零声母
#0 #1 #2 #3 表示韵律或者停顿的级别，这里没有用到
eos 表示 end of string
sp 表示 暂停还是吸气之类的噪声，我也比较迷糊
sil 表示静音

**Comment by zdj97** [comment]
噢噢  如果换一套建模单位的话，像^这种是不是可以去掉了

**Comment by MaxMax2016** [comment]
是的，可以完全重新设计一套建模单元

**Comment by zdj97** [comment]
好的
