### ISSUE TITLE
infer loss

### ISSUE THREAD

**Issue by zdj97** [PlayVoice/vits_chinese#74]
infer loss这块的目的是什么呢？

**Comment by MaxMax2016** [comment]
我这里测试，他能减少中文发音错误

**Comment by zdj97** [comment]
ok  然后自己的一个经验吧  就是替换音素建模单位后，最好不保留首尾的sil标签，要不然会出现首尾吞半个发音的情况
大佬这个项目有下一步计划不

**Comment by MaxMax2016** [comment]
应该没了，最多加个pitch预测，然后hifigan修改为nsf hifigan，尝试解决偶发的断音
