### ISSUE TITLE
刚接触vits，请问训练自己的模型只需要把标贝的数据替换成自己的数据集就可以了吗

### ISSUE THREAD

**Issue by vingin007** [PlayVoice/vits_chinese#75]

**Comment by MaxMax2016** [comment]
您的数据和标贝数据有哪些差异呢？标注格式不一样的话，需要修改一下数据预处理。

**Comment by vingin007** [comment]
只需要txt和wav文件对吗大佬，我有大概2000条wav可以训练出好点的效果吗

**Comment by vingin007** [comment]
txt我是按照标贝的格式在标注的

**Comment by MaxMax2016** [comment]
2000条少了点点，如果是高质量女声，可以尝试在标贝训练好的模型进行继续训练

**Comment by MaxMax2016** [comment]
> txt我是按照标贝的格式在标注的

那就可以

**Comment by vingin007** [comment]
我是男声。如果是10000条是不是可以得到和标贝训练相同的结果。。不对比数据集质量的话

**Comment by MaxMax2016** [comment]
> 我是男声。如果是10000条是不是可以得到和标贝训练相同的结果。。不对比数据集质量的话

是的

**Comment by vingin007** [comment]
好的，感谢大佬
