### ISSUE TITLE
数字念不出来啊

### ISSUE THREAD

**Issue by stevezhang88** [PlayVoice/vits_chinese#77]
比如，今天准备50个苹果。 其中，50念不出来。 出发改成 “五十”

**Comment by MaxMax2016** [comment]
这不是一个完整的TTS工程，要实现文本正则需要做如下工作：

> Text normlize
> pip install WeTextProcessing
> 
> from tn.chinese.normalizer import Normalizer
> 
> normalizer = Normalizer()
> 
> ...
> 
> item = fo.readline().strip()
> 
> item = normalizer.normalize(item)
