### ISSUE TITLE
试了下效果还可以，就是默认模型不支持读数字和英文，感觉有点限制

### ISSUE THREAD

**Issue by futureflsl** [PlayVoice/vits_chinese#82]
作者能不能更新下支持中文英文数字读取，那样就太好了

**Comment by MaxMax2016** [comment]
数字见这个 https://github.com/PlayVoice/vits_chinese/issues/77

英语的问题是：目前没有开源的中英双语数据

**Comment by GanymedeNil** [comment]
> 数字见这个 #77
> 
> 英语的问题是：目前没有开源的中英双语数据

国内有开源过中英双语的数据 https://huggingface.co/csukuangfj/tal_csasr

**Comment by dnlzsy** [comment]
请问中英文和数字混合的语句如何标注拼音？是数字和英文直接放在拼音中间马？
