### ISSUE TITLE
训练1400多轮了，合成不出任何声音是为什么呢

### ISSUE THREAD

**Issue by jmaxzh** [PlayVoice/vits_chinese#83]
单人数据集，训练集 2k 条，验证集 200 条。

数据集的音频格式
```shell
Input #0, wav, from 'processed_12493.wav':
  Duration: 00:00:01.26, bitrate: 705 kb/s
    Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 22050 Hz, 1 channels, flt, 705 kb/s
```

训练集和验证集格式`./data/waves/processed_12910.wav|./data/temps/processed_12910.spec.pt|./data/berts/processed_12910.npy|sil ^ o2 sp d uei4 l e5 ^ ai1 ^ ia1 sp sh iii4 q ing2 sh iii4 zh e4 ^ iang4 d e5 sp sil`

配置文件, 改动了 `batch_size` 和 `learning_rate`, `sampling_rate` 从 16000 调整为 22050
```json
{
  "train": {
    "train_class": "models.SynthesizerTrn",
    "eval_class": "models.SynthesizerEval",
    "log_interval": 100,
    "eval_interval": 10000,
    "seed": 1234,
    "epochs": 20000,
    "learning_rate": 2e-4,
    "betas": [0.8, 0.99],
    "eps": 1e-9,
    "batch_size": 64,
    "fp16_run": false,
    "lr_decay": 0.999875,
    "segment_size": 12800,
    "init_lr_ratio": 1,
    "warmup_epochs": 0,
    "c_mel": 45,
    "c_kl": 1.0
  },
  "data": {
    "training_files": "filelists/train.txt",
    "validation_files": "filelists/valid.txt",
    "origin_training_files": "filelists/paimon_train.txt",
    "origin_validation_files": "filelists/paimon_val.txt",
    "max_wav_value": 32768.0,
    "sampling_rate": 22050,
    "filter_length": 1024,
    "hop_length": 256,
    "win_length": 1024,
    "n_mel_channels": 80,
    "mel_fmin": 0.0,
    "mel_fmax": null,
    "add_blank": false,
    "n_speakers": 0
  },
  "model": {
    "inter_channels": 192,
    "hidden_channels": 192,
    "filter_channels": 768,
    "n_heads": 2,
    "n_layers": 6,
    "kernel_size": 3,
    "p_dropout": 0.1,
    "resblock": "1",
    "resblock_kernel_sizes": [3,7,11],
    "resblock_dilation_sizes": [[1,3,5], [1,3,5], [1,3,5]],
    "upsample_rates": [8,8,2,2],
    "upsample_initial_channel": 512,
    "upsample_kernel_sizes": [16,16,4,4],
    "n_layers_q": 3,
    "use_spectral_norm": false
  }
}
````

训练了 1400 轮了
```shell
INFO    Train Epoch: 1426 [0%]
INFO    [39900, 0.0001673656990282196]
INFO    loss_disc=3.000, loss_gen=1.498, loss_fm=0.000
INFO    loss_mel=0.233, loss_dur=0.999, loss_kl=-0.212
INFO    loss_kl_r=0.054
INFO    ====> Epoch: 1426
INFO    ====> Epoch: 1427
INFO    ====> Epoch: 1428
INFO    Train Epoch: 1429 [57%]
INFO    [40000, 0.00016730294473602428]
INFO    loss_disc=3.000, loss_gen=1.497, loss_fm=0.000
INFO    loss_mel=0.238, loss_dur=0.946, loss_kl=-0.168
INFO    loss_kl_r=-0.002
INFO    Saving model and optimizer state at iteration 1429 to ./output/paimon/G_40000.pth
INFO    Saving model and optimizer state at iteration 1429 to ./output/paimon/D_40000.pth
INFO    ====> Epoch: 1429
```

推理的命令 `python vits_infer.py --config configs/my.json --model ./logs/my/G_40000.pth`

**Comment by MaxMax2016** [comment]
loss_mel通常为18左右，而，log中为0.23；loss_fm也不可能等于0

**Comment by jmaxzh** [comment]
> loss_mel通常为18左右，而，log中为0.23；loss_fm也不可能等于0

可能是什么原因呢？是训练集准备的不对吗

**Comment by MaxMax2016** [comment]
音频文件可能有问题

**Comment by jmaxzh** [comment]
> 音频文件可能有问题

调整了音频文件后，重新开始训练了。这样看起来正常了吗？
```bash
2023-06-05 22:26:23,197 paimon  INFO    {'train': {'train_class': 'models.SynthesizerTrn', 'eval_class': 'models.SynthesizerEval', 'log_interval': 100, 'eval_interval': 10000, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 64, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/valid.txt', 'origin_training_files': 'filelists/paimon_train.txt', 'origin_validation_files': 'filelists/paimon_val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': False, 'n_speakers': 0}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False}, 'model_dir': './output/paimon'}
2023-06-05 22:26:25,170 paimon  INFO    no teacher model.
2023-06-05 22:27:19,209 paimon  INFO    Train Epoch: 1 [0%]
2023-06-05 22:27:19,209 paimon  INFO    [0, 0.0002]
2023-06-05 22:27:19,209 paimon  INFO    loss_disc=6.159, loss_gen=4.615, loss_fm=0.505
2023-06-05 22:27:19,209 paimon  INFO    loss_mel=106.741, loss_dur=2.049, loss_kl=217.816
2023-06-05 22:27:19,209 paimon  INFO    loss_kl_r=227.183
2023-06-05 22:28:02,268 paimon  INFO    Saving model and optimizer state at iteration 1 to ./output/paimon/G_0.pth
2023-06-05 22:28:02,682 paimon  INFO    Saving model and optimizer state at iteration 1 to ./output/paimon/D_0.pth
2023-06-05 22:29:40,677 paimon  INFO    ====> Epoch: 1
2023-06-05 22:30:41,315 paimon  INFO    ====> Epoch: 2
2023-06-05 22:31:55,198 paimon  INFO    Train Epoch: 3 [94%]
2023-06-05 22:31:55,199 paimon  INFO    [100, 0.000199950003125]
2023-06-05 22:31:55,199 paimon  INFO    loss_disc=1.565, loss_gen=3.118, loss_fm=6.872
2023-06-05 22:31:55,199 paimon  INFO    loss_mel=43.492, loss_dur=1.538, loss_kl=2.353
2023-06-05 22:31:55,199 paimon  INFO    loss_kl_r=4.249
2023-06-05 22:31:57,106 paimon  INFO    ====> Epoch: 3
```

**Comment by MaxMax2016** [comment]
比较正常

**Comment by yjp999** [comment]
> > 音频文件可能有问题
> 
> 调整了音频文件后，重新开始训练了。这样看起来正常了吗？
> 
> ```shell
> 2023-06-05 22:26:23,197 paimon  INFO    {'train': {'train_class': 'models.SynthesizerTrn', 'eval_class': 'models.SynthesizerEval', 'log_interval': 100, 'eval_interval': 10000, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 64, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/valid.txt', 'origin_training_files': 'filelists/paimon_train.txt', 'origin_validation_files': 'filelists/paimon_val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': False, 'n_speakers': 0}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False}, 'model_dir': './output/paimon'}
> 2023-06-05 22:26:25,170 paimon  INFO    no teacher model.
> 2023-06-05 22:27:19,209 paimon  INFO    Train Epoch: 1 [0%]
> 2023-06-05 22:27:19,209 paimon  INFO    [0, 0.0002]
> 2023-06-05 22:27:19,209 paimon  INFO    loss_disc=6.159, loss_gen=4.615, loss_fm=0.505
> 2023-06-05 22:27:19,209 paimon  INFO    loss_mel=106.741, loss_dur=2.049, loss_kl=217.816
> 2023-06-05 22:27:19,209 paimon  INFO    loss_kl_r=227.183
> 2023-06-05 22:28:02,268 paimon  INFO    Saving model and optimizer state at iteration 1 to ./output/paimon/G_0.pth
> 2023-06-05 22:28:02,682 paimon  INFO    Saving model and optimizer state at iteration 1 to ./output/paimon/D_0.pth
> 2023-06-05 22:29:40,677 paimon  INFO    ====> Epoch: 1
> 2023-06-05 22:30:41,315 paimon  INFO    ====> Epoch: 2
> 2023-06-05 22:31:55,198 paimon  INFO    Train Epoch: 3 [94%]
> 2023-06-05 22:31:55,199 paimon  INFO    [100, 0.000199950003125]
> 2023-06-05 22:31:55,199 paimon  INFO    loss_disc=1.565, loss_gen=3.118, loss_fm=6.872
> 2023-06-05 22:31:55,199 paimon  INFO    loss_mel=43.492, loss_dur=1.538, loss_kl=2.353
> 2023-06-05 22:31:55,199 paimon  INFO    loss_kl_r=4.249
> 2023-06-05 22:31:57,106 paimon  INFO    ====> Epoch: 3
> ```

我也遇到了infer没有声音 同样的问题，请问你是怎么修复音频文件的？

**Comment by jmaxzh** [comment]
> > > 音频文件可能有问题
> > 
> > 
> > 调整了音频文件后，重新开始训练了。这样看起来正常了吗？
> > ```shell
> > 2023-06-05 22:26:23,197 paimon  INFO    {'train': {'train_class': 'models.SynthesizerTrn', 'eval_class': 'models.SynthesizerEval', 'log_interval': 100, 'eval_interval': 10000, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 64, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/valid.txt', 'origin_training_files': 'filelists/paimon_train.txt', 'origin_validation_files': 'filelists/paimon_val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': False, 'n_speakers': 0}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False}, 'model_dir': './output/paimon'}
> > 2023-06-05 22:26:25,170 paimon  INFO    no teacher model.
> > 2023-06-05 22:27:19,209 paimon  INFO    Train Epoch: 1 [0%]
> > 2023-06-05 22:27:19,209 paimon  INFO    [0, 0.0002]
> > 2023-06-05 22:27:19,209 paimon  INFO    loss_disc=6.159, loss_gen=4.615, loss_fm=0.505
> > 2023-06-05 22:27:19,209 paimon  INFO    loss_mel=106.741, loss_dur=2.049, loss_kl=217.816
> > 2023-06-05 22:27:19,209 paimon  INFO    loss_kl_r=227.183
> > 2023-06-05 22:28:02,268 paimon  INFO    Saving model and optimizer state at iteration 1 to ./output/paimon/G_0.pth
> > 2023-06-05 22:28:02,682 paimon  INFO    Saving model and optimizer state at iteration 1 to ./output/paimon/D_0.pth
> > 2023-06-05 22:29:40,677 paimon  INFO    ====> Epoch: 1
> > 2023-06-05 22:30:41,315 paimon  INFO    ====> Epoch: 2
> > 2023-06-05 22:31:55,198 paimon  INFO    Train Epoch: 3 [94%]
> > 2023-06-05 22:31:55,199 paimon  INFO    [100, 0.000199950003125]
> > 2023-06-05 22:31:55,199 paimon  INFO    loss_disc=1.565, loss_gen=3.118, loss_fm=6.872
> > 2023-06-05 22:31:55,199 paimon  INFO    loss_mel=43.492, loss_dur=1.538, loss_kl=2.353
> > 2023-06-05 22:31:55,199 paimon  INFO    loss_kl_r=4.249
> > 2023-06-05 22:31:57,106 paimon  INFO    ====> Epoch: 3
> > ```
> 
> 我也遇到了infer没有声音 同样的问题，请问你是怎么修复音频文件的？

用 au 重新对原始音频文件进行转格式。之前不是用 au，用的 python 代码。

**Comment by scriptboy1990** [comment]
> > > > 音频文件可能有问题
> > > 
> > > 
> > > 调整了音频文件后，重新开始训练了。这样看起来正常了吗？
> > > ```shell
> > > 2023-06-05 22:26:23,197 paimon  INFO    {'train': {'train_class': 'models.SynthesizerTrn', 'eval_class': 'models.SynthesizerEval', 'log_interval': 100, 'eval_interval': 10000, 'seed': 1234, 'epochs': 20000, 'learning_rate': 0.0002, 'betas': [0.8, 0.99], 'eps': 1e-09, 'batch_size': 64, 'fp16_run': False, 'lr_decay': 0.999875, 'segment_size': 12800, 'init_lr_ratio': 1, 'warmup_epochs': 0, 'c_mel': 45, 'c_kl': 1.0}, 'data': {'training_files': 'filelists/train.txt', 'validation_files': 'filelists/valid.txt', 'origin_training_files': 'filelists/paimon_train.txt', 'origin_validation_files': 'filelists/paimon_val.txt', 'max_wav_value': 32768.0, 'sampling_rate': 22050, 'filter_length': 1024, 'hop_length': 256, 'win_length': 1024, 'n_mel_channels': 80, 'mel_fmin': 0.0, 'mel_fmax': None, 'add_blank': False, 'n_speakers': 0}, 'model': {'inter_channels': 192, 'hidden_channels': 192, 'filter_channels': 768, 'n_heads': 2, 'n_layers': 6, 'kernel_size': 3, 'p_dropout': 0.1, 'resblock': '1', 'resblock_kernel_sizes': [3, 7, 11], 'resblock_dilation_sizes': [[1, 3, 5], [1, 3, 5], [1, 3, 5]], 'upsample_rates': [8, 8, 2, 2], 'upsample_initial_channel': 512, 'upsample_kernel_sizes': [16, 16, 4, 4], 'n_layers_q': 3, 'use_spectral_norm': False}, 'model_dir': './output/paimon'}
> > > 2023-06-05 22:26:25,170 paimon  INFO    no teacher model.
> > > 2023-06-05 22:27:19,209 paimon  INFO    Train Epoch: 1 [0%]
> > > 2023-06-05 22:27:19,209 paimon  INFO    [0, 0.0002]
> > > 2023-06-05 22:27:19,209 paimon  INFO    loss_disc=6.159, loss_gen=4.615, loss_fm=0.505
> > > 2023-06-05 22:27:19,209 paimon  INFO    loss_mel=106.741, loss_dur=2.049, loss_kl=217.816
> > > 2023-06-05 22:27:19,209 paimon  INFO    loss_kl_r=227.183
> > > 2023-06-05 22:28:02,268 paimon  INFO    Saving model and optimizer state at iteration 1 to ./output/paimon/G_0.pth
> > > 2023-06-05 22:28:02,682 paimon  INFO    Saving model and optimizer state at iteration 1 to ./output/paimon/D_0.pth
> > > 2023-06-05 22:29:40,677 paimon  INFO    ====> Epoch: 1
> > > 2023-06-05 22:30:41,315 paimon  INFO    ====> Epoch: 2
> > > 2023-06-05 22:31:55,198 paimon  INFO    Train Epoch: 3 [94%]
> > > 2023-06-05 22:31:55,199 paimon  INFO    [100, 0.000199950003125]
> > > 2023-06-05 22:31:55,199 paimon  INFO    loss_disc=1.565, loss_gen=3.118, loss_fm=6.872
> > > 2023-06-05 22:31:55,199 paimon  INFO    loss_mel=43.492, loss_dur=1.538, loss_kl=2.353
> > > 2023-06-05 22:31:55,199 paimon  INFO    loss_kl_r=4.249
> > > 2023-06-05 22:31:57,106 paimon  INFO    ====> Epoch: 3
> > > ```
> > 
> > 
> > 我也遇到了infer没有声音 同样的问题，请问你是怎么修复音频文件的？
> 
> 用 au 重新对原始音频文件进行转格式。之前不是用 au，用的 python 代码。

原始音频文件不是wav吗？我也遇到了没声音的问题。

**Comment by MaxMax2016** [comment]
## 采样率转换
```
python prep_resample.py --wav aishell-3/train/wav/ --out vits_data/waves-16k
```
用这个处理过了吗？
