### ISSUE TITLE
train.txt格式

### ISSUE THREAD

**Issue by caifangvip** [PlayVoice/vits_chinese#89]
scrips.append(
            f"./data/waves/{fileidx}.wav|./data/temps/{fileidx}.spec.pt|./data/berts/{fileidx}.npy|{phone_items_str}")
看到代码里会写入./data/temps/{fileidx}.spec.pt，
但是filelists里面文件里却没有。

**Comment by MaxMax2016** [comment]
代码优化的时候，忘记更新处理后的filelists了
