### ISSUE TITLE
vocab.txt里没有的字报错

### ISSUE THREAD

**Issue by yihuitang** [PlayVoice/vits_chinese#93]
使用vits_prepare_4_custom_speaker.py处理自定义的数据集时报错：

Traceback (most recent call last):
  File "vits_prepare_4_custom_speaker.py", line 79, in <module>
    phone_items_str, char_embeds = pinyin_generator.chinese_to_phonemes(content)
  File "/root/vits_chinese/vits_pinyin.py", line 56, in chinese_to_phonemes
    assert not tokens.count("[UNK]")
AssertionError

文本内容是这样的：寅吃卯粮，无异于饮鸩止渴。
检查发现vocab.txt里没有“鸩”字，类似的字还有“馓”、“莜”，都会报同样的错误。

请问这种情况怎么处理？

**Comment by MaxMax2016** [comment]
换bert vits分支试试

**Comment by yihuitang** [comment]
在vits_prepare.py基础上修改了个[脚本](https://github.com/yihuitang/vits_chinese/blob/master/vits_prepare_4_custom_speaker2.py)，可以了正常生成filelist和训练了
