### ISSUE TITLE
请问bert模型prosody_model.pt每次更换自己的数据时，需要用自己的数据重新训练prosody_model.pt吗

### ISSUE THREAD

**Issue by huangmeimao** [PlayVoice/vits_chinese#98]
期待您的回复

**Comment by MaxMax2016** [comment]
不用的

**Comment by huangmeimao** [comment]
好的，多谢了

**Comment by SRbone** [comment]
大佬，这个./bert/prosody_model.pt 是不是有关韵律的？prosody_model.pt在哪训练得到的？有没有自己训练的方法或链接啊？
:-）

**Comment by MaxMax2016** [comment]
使用这个项目的https://github.com/Executedone/Chinese-FastSpeech2
相关资料在 https://zhuanlan.zhihu.com/p/585086910

**Comment by SRbone** [comment]
多谢大佬，我去看看。

**Comment by zhaojingxin123** [comment]
> prosody_model.pt

从哪里下载prosody_model.pt文件呀？
