### ISSUE TITLE
模型大小

### ISSUE THREAD

**Issue by huangmeimao** [PlayVoice/vits_chinese#99]
如果用默认参数训练的模型大小400M，您提供的模型是136M左右，不是student,请问是什么原因？多谢

**Comment by MaxMax2016** [comment]
400的是包含了优化器

**Comment by huangmeimao** [comment]
刚看了训练过程中都使用了优化器，您在其他人的问题中提供的train.log里也有使用，所以您最终提供的模型是另外加载保存的模型吗？我看推理过程中加载模型并没有使用优化器

**Comment by MaxMax2016** [comment]
推理代码vits-infer中有相关模型导出代码，屏蔽的那几行。
